from PyQt6 import QtCore, QtGui, QtWidgets
#from waterpybal.dataset_prep import netCDF_ds

class Ui_lat_lon_Window(object):

    #select raster file
    def selectFile(self):
        filter = "Raster(*.tiff)"
        self.fileName = QtWidgets.QFileDialog.getOpenFileName(caption='select raster file',filter=filter)[0]
        
        self.lineEdit_xyraster.setText(self.fileName)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(509, 476)
        MainWindow.setMaximumSize(QtCore.QSize(2000, 750))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_spatialtemporal = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_spatialtemporal.setFont(font)
        self.groupBox_spatialtemporal.setObjectName("groupBox_spatialtemporal")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_spatialtemporal)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_xy_raster = QtWidgets.QLabel(self.groupBox_spatialtemporal)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_xy_raster.setFont(font)
        self.label_xy_raster.setObjectName("label_xy_raster")
        self.horizontalLayout_5.addWidget(self.label_xy_raster)
        self.lineEdit_xyraster = QtWidgets.QLineEdit(self.groupBox_spatialtemporal)
        self.lineEdit_xyraster.setMinimumSize(QtCore.QSize(160, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_xyraster.setFont(font)
        self.lineEdit_xyraster.setObjectName("lineEdit_xyraster")
        self.horizontalLayout_5.addWidget(self.lineEdit_xyraster)

        #browse button raster
        self.toolButton_browse_xy_raster = QtWidgets.QToolButton(self.groupBox_spatialtemporal,clicked=lambda:self.selectFile())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_browse_xy_raster.sizePolicy().hasHeightForWidth())
        self.toolButton_browse_xy_raster.setSizePolicy(sizePolicy)
        self.toolButton_browse_xy_raster.setMaximumSize(QtCore.QSize(20, 20))
        self.toolButton_browse_xy_raster.setObjectName("toolButton_browse_xy_raster")
        self.horizontalLayout_5.addWidget(self.toolButton_browse_xy_raster)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(471, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_time_interval = QtWidgets.QLabel(self.groupBox_spatialtemporal)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_time_interval.setFont(font)
        self.label_time_interval.setObjectName("label_time_interval")
        self.horizontalLayout_3.addWidget(self.label_time_interval)
        self.comboBox_time_interval = QtWidgets.QComboBox(self.groupBox_spatialtemporal)
        self.comboBox_time_interval.setMinimumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_time_interval.setFont(font)
        self.comboBox_time_interval.setObjectName("comboBox_time_interval")
        self.comboBox_time_interval.addItem("")
        self.comboBox_time_interval.addItem("")
        self.comboBox_time_interval.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_time_interval)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_6.addItem(spacerItem4)
        self.splitter = QtWidgets.QSplitter(self.groupBox_spatialtemporal)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_5.addItem(spacerItem5)
        self.label_start_time = QtWidgets.QLabel(self.layoutWidget)
        self.label_start_time.setMinimumSize(QtCore.QSize(35, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_start_time.setFont(font)
        self.label_start_time.setObjectName("label_start_time")
        self.verticalLayout_5.addWidget(self.label_start_time)
        self.label_end_time = QtWidgets.QLabel(self.layoutWidget)
        self.label_end_time.setMinimumSize(QtCore.QSize(35, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_end_time.setFont(font)
        self.label_end_time.setObjectName("label_end_time")
        self.verticalLayout_5.addWidget(self.label_end_time)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_hour = QtWidgets.QLabel(self.layoutWidget)
        self.label_hour.setMinimumSize(QtCore.QSize(50, 20))
        self.label_hour.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_hour.setFont(font)
        self.label_hour.setObjectName("label_hour")
        self.verticalLayout.addWidget(self.label_hour)
        self.comboBox_start_hour = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_start_hour.sizePolicy().hasHeightForWidth())
        self.comboBox_start_hour.setSizePolicy(sizePolicy)
        self.comboBox_start_hour.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_start_hour.setFont(font)
        self.comboBox_start_hour.setObjectName("comboBox_start_hour")
        for i in range (0,24):
            self.comboBox_start_hour.addItem("")

        self.verticalLayout.addWidget(self.comboBox_start_hour)
        self.comboBox_end_hour = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_end_hour.sizePolicy().hasHeightForWidth())
        self.comboBox_end_hour.setSizePolicy(sizePolicy)
        self.comboBox_end_hour.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_end_hour.setFont(font)
        self.comboBox_end_hour.setObjectName("comboBox_end_hour")
        for i in range (0,24):
            self.comboBox_end_hour.addItem("")

        self.verticalLayout.addWidget(self.comboBox_end_hour)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_day = QtWidgets.QLabel(self.layoutWidget)
        self.label_day.setMinimumSize(QtCore.QSize(50, 20))
        self.label_day.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_day.setFont(font)
        self.label_day.setObjectName("label_day")
        self.verticalLayout_2.addWidget(self.label_day)
        self.comboBox_start_day = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_start_day.sizePolicy().hasHeightForWidth())
        self.comboBox_start_day.setSizePolicy(sizePolicy)
        self.comboBox_start_day.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_start_day.setFont(font)
        self.comboBox_start_day.setObjectName("comboBox_start_day")
        for i in range (0,30):
            self.comboBox_start_day.addItem("")

        self.verticalLayout_2.addWidget(self.comboBox_start_day)
        self.comboBox_end_day = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_end_day.sizePolicy().hasHeightForWidth())
        self.comboBox_end_day.setSizePolicy(sizePolicy)
        self.comboBox_end_day.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_end_day.setFont(font)
        self.comboBox_end_day.setObjectName("comboBox_end_day")
        for i in range (0,30):
            self.comboBox_end_day.addItem("")

        self.verticalLayout_2.addWidget(self.comboBox_end_day)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_month = QtWidgets.QLabel(self.layoutWidget)
        self.label_month.setMinimumSize(QtCore.QSize(50, 20))
        self.label_month.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_month.setFont(font)
        self.label_month.setObjectName("label_month")
        self.verticalLayout_3.addWidget(self.label_month)
        self.comboBox_start_month = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_start_month.sizePolicy().hasHeightForWidth())
        self.comboBox_start_month.setSizePolicy(sizePolicy)
        self.comboBox_start_month.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_start_month.setFont(font)
        self.comboBox_start_month.setObjectName("comboBox_start_month")
        for i in range (0,12):
            self.comboBox_start_month.addItem("")

        self.verticalLayout_3.addWidget(self.comboBox_start_month)
        self.comboBox_end_month = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_end_month.sizePolicy().hasHeightForWidth())
        self.comboBox_end_month.setSizePolicy(sizePolicy)
        self.comboBox_end_month.setMinimumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_end_month.setFont(font)
        self.comboBox_end_month.setObjectName("comboBox_end_month")
        for i in range (0,12):
            self.comboBox_end_month.addItem("")

        self.verticalLayout_3.addWidget(self.comboBox_end_month)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_year = QtWidgets.QLabel(self.layoutWidget)
        self.label_year.setMinimumSize(QtCore.QSize(50, 20))
        self.label_year.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_year.setFont(font)
        self.label_year.setObjectName("label_year")
        self.verticalLayout_4.addWidget(self.label_year)
        self.lineEdit_start_year = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_start_year.setMinimumSize(QtCore.QSize(50, 20))
        self.lineEdit_start_year.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_start_year.setFont(font)
        self.lineEdit_start_year.setObjectName("lineEdit_start_year")
        self.verticalLayout_4.addWidget(self.lineEdit_start_year)
        self.lineEdit_end_year = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_end_year.setMinimumSize(QtCore.QSize(50, 20))
        self.lineEdit_end_year.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_end_year.setFont(font)
        self.lineEdit_end_year.setObjectName("lineEdit_end_year")
        self.verticalLayout_4.addWidget(self.lineEdit_end_year)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addWidget(self.splitter)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addWidget(self.groupBox_spatialtemporal)
        self.groupBox_additional_vars = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_additional_vars.setMinimumSize(QtCore.QSize(275, 235))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_additional_vars.setFont(font)
        self.groupBox_additional_vars.setObjectName("groupBox_additional_vars")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_additional_vars)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.tableWidget_additional_vars = QtWidgets.QTableWidget(self.groupBox_additional_vars)
        self.tableWidget_additional_vars.setObjectName("tableWidget_additional_vars")
        self.tableWidget_additional_vars.setColumnCount(2)
        self.tableWidget_additional_vars.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_additional_vars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_additional_vars.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_2.addWidget(self.tableWidget_additional_vars)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.toolButton_new = QtWidgets.QToolButton(self.groupBox_additional_vars)
        self.toolButton_new.setMinimumSize(QtCore.QSize(70, 25))
        self.toolButton_new.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.toolButton_new.setObjectName("toolButton_new")
        self.verticalLayout_10.addWidget(self.toolButton_new)
        self.toolButton_remove = QtWidgets.QToolButton(self.groupBox_additional_vars)
        self.toolButton_remove.setMinimumSize(QtCore.QSize(70, 25))
        self.toolButton_remove.setObjectName("toolButton_remove")
        self.verticalLayout_10.addWidget(self.toolButton_remove)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addWidget(self.groupBox_additional_vars)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.buttonBox_main_lat_lon_win = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox_main_lat_lon_win.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox_main_lat_lon_win.setObjectName("buttonBox_main_lat_lon_win")
        self.horizontalLayout_6.addWidget(self.buttonBox_main_lat_lon_win)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        #connect the ok cancel buttons
        ds1=self.buttonBox_main_lat_lon_win.accepted.connect(MainWindow.accept)
        ds2=self.buttonBox_main_lat_lon_win.rejected.connect(MainWindow.reject)
        '''    netCDF_ds.ds_dimensions(
                lat_lon_type="raster",
                lat_lon_source=self.lineEdit_xyraster.text(),
                time_source=None,
                time_type="time_dic",
                lat_name=None,
                lon_name=None,
                time_name=None,
                border_res_dic=None,
                time_dic={
                    "start":[self.lineEdit_start_year.text(),self.comboBox_start_month.currentText(),self.comboBox_start_day.currentText(),self.comboBox_start_hour.currentText()],
                    "end":[self.lineEdit_end_year.text(),self.comboBox_end_month.currentText(),self.comboBox_end_day.currentText(),self.comboBox_end_hour.currentText()]
                },
                preferred_date_interval=self.comboBox_time_interval.currentText()
            ))'''
        print (ds1,ds2)
        #self.buttonBox_main_lat_lon_win.rejected.connect(self.reject)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_spatialtemporal.setTitle(_translate("MainWindow", "Spatial -Temporal properties"))
        self.label_xy_raster.setText(_translate("MainWindow", "Raster to determine Spatial properties (X and Y) :"))
        self.toolButton_browse_xy_raster.setText(_translate("MainWindow", "..."))
        self.label_time_interval.setText(_translate("MainWindow", "Time interval: "))
        self.comboBox_time_interval.setItemText(0, _translate("MainWindow", "Daily"))
        self.comboBox_time_interval.setItemText(1, _translate("MainWindow", "Monthly"))
        self.comboBox_time_interval.setItemText(2, _translate("MainWindow", "Hourly"))
        self.label_start_time.setText(_translate("MainWindow", "Start"))
        self.label_end_time.setText(_translate("MainWindow", "End"))
        self.label_hour.setText(_translate("MainWindow", "Hour"))
        for i in range(0,24):
            self.comboBox_start_hour.setItemText(i, _translate("MainWindow", str(i)))
            self.comboBox_end_hour.setItemText(i, _translate("MainWindow", str(i)))

        self.label_day.setText(_translate("MainWindow", "Day"))

        for i in range(0,30):
            self.comboBox_start_day.setItemText(i, _translate("MainWindow", str(i+1)))
            self.comboBox_end_day.setItemText(i, _translate("MainWindow", str(i+1)))

        self.label_month.setText(_translate("MainWindow", "Month"))

        for i in range(0,12):
            self.comboBox_start_month.setItemText(i, _translate("MainWindow", str(i+1)))
            self.comboBox_end_month.setItemText(i, _translate("MainWindow", str(i+1)))

        self.label_year.setText(_translate("MainWindow", "Year"))
        self.groupBox_additional_vars.setTitle(_translate("MainWindow", "Additional Variables"))
        item = self.tableWidget_additional_vars.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Var. Name"))
        item = self.tableWidget_additional_vars.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Var. Unit"))
        self.toolButton_new.setText(_translate("MainWindow", "New"))
        self.toolButton_remove.setText(_translate("MainWindow", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_lat_lon_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
