# Form implementation generated from reading ui file 'balance.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_balance_Dialog(object):
    def setupUi(self, balance_Dialog):
        balance_Dialog.setObjectName("balance_Dialog")
        balance_Dialog.resize(241, 60)
        self.verticalLayout = QtWidgets.QVBoxLayout(balance_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_init_swr = QtWidgets.QLabel(balance_Dialog)
        self.label_init_swr.setMinimumSize(QtCore.QSize(210, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_init_swr.setFont(font)
        self.label_init_swr.setObjectName("label_init_swr")
        self.horizontalLayout.addWidget(self.label_init_swr)
        self.lineEdit_init_swr = QtWidgets.QLineEdit(balance_Dialog)
        self.lineEdit_init_swr.setMinimumSize(QtCore.QSize(40, 20))
        self.lineEdit_init_swr.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_init_swr.setObjectName("lineEdit_init_swr")
        self.horizontalLayout.addWidget(self.lineEdit_init_swr)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(balance_Dialog)
        self.buttonBox.setMaximumSize(QtCore.QSize(600, 200))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(balance_Dialog)
        self.buttonBox.accepted.connect(balance_Dialog.accept)
        self.buttonBox.rejected.connect(balance_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(balance_Dialog)

    def retranslateUi(self, balance_Dialog):
        _translate = QtCore.QCoreApplication.translate
        balance_Dialog.setWindowTitle(_translate("balance_Dialog", "Balance calculation"))
        self.label_init_swr.setText(_translate("balance_Dialog", "Initial Soil Water Reserve Percentage"))
        self.lineEdit_init_swr.setText(_translate("balance_Dialog", "100"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    balance_Dialog = QtWidgets.QDialog()
    ui = Ui_balance_Dialog()
    ui.setupUi(balance_Dialog)
    balance_Dialog.show()
    sys.exit(app.exec())
