# Form implementation generated from reading ui file 'etp_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_etp(object):
    def setupUi(self, Dialog_etp):
        Dialog_etp.setObjectName("Dialog_etp")
        Dialog_etp.resize(301, 269)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_etp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_method = QtWidgets.QLabel(Dialog_etp)
        self.label_method.setMinimumSize(QtCore.QSize(45, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_method.setFont(font)
        self.label_method.setObjectName("label_method")
        self.horizontalLayout.addWidget(self.label_method)
        self.comboBox_etp_method = QtWidgets.QComboBox(Dialog_etp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_etp_method.sizePolicy().hasHeightForWidth())
        self.comboBox_etp_method.setSizePolicy(sizePolicy)
        self.comboBox_etp_method.setMinimumSize(QtCore.QSize(70, 20))
        self.comboBox_etp_method.setObjectName("comboBox_etp_method")
        self.horizontalLayout.addWidget(self.comboBox_etp_method)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget_etp_method_params = QtWidgets.QTableWidget(Dialog_etp)
        self.tableWidget_etp_method_params.setObjectName("tableWidget_etp_method_params")
        self.tableWidget_etp_method_params.setColumnCount(3)
        self.tableWidget_etp_method_params.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_etp_method_params.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_etp_method_params.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_etp_method_params.setHorizontalHeaderItem(2, item)
        self.tableWidget_etp_method_params.horizontalHeader().setDefaultSectionSize(90)
        self.verticalLayout.addWidget(self.tableWidget_etp_method_params)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_etp)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_etp)
        self.buttonBox.accepted.connect(Dialog_etp.accept)
        self.buttonBox.rejected.connect(Dialog_etp.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_etp)

    def retranslateUi(self, Dialog_etp):
        _translate = QtCore.QCoreApplication.translate
        Dialog_etp.setWindowTitle(_translate("Dialog_etp", "ETP Calculation"))
        self.label_method.setText(_translate("Dialog_etp", "Method"))
        item = self.tableWidget_etp_method_params.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_etp", "Parameter"))
        item = self.tableWidget_etp_method_params.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_etp", "Type"))
        item = self.tableWidget_etp_method_params.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_etp", "Value or Path"))


'''if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_etp = QtWidgets.QDialog()
    ui = Ui_Dialog_etp()
    ui.setupUi(Dialog_etp)
    Dialog_etp.show()
    sys.exit(app.exec())'''
