# Form implementation generated from reading ui file 'etp_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_etp(object):
    def setupUi(self, Dialog_etp):
        Dialog_etp.setObjectName("Dialog_etp")
        Dialog_etp.resize(950, 530)
        Dialog_etp.setMinimumSize(QtCore.QSize(950, 530))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog_etp)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_method = QtWidgets.QLabel(Dialog_etp)
        self.label_method.setMinimumSize(QtCore.QSize(45, 20))
        self.label_method.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_method.setFont(font)
        self.label_method.setObjectName("label_method")
        self.horizontalLayout.addWidget(self.label_method)
        self.comboBox_etp_method = QtWidgets.QComboBox(Dialog_etp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_etp_method.sizePolicy().hasHeightForWidth())
        self.comboBox_etp_method.setSizePolicy(sizePolicy)
        self.comboBox_etp_method.setMinimumSize(QtCore.QSize(70, 20))
        self.comboBox_etp_method.setMaximumSize(QtCore.QSize(360, 16777215))
        self.comboBox_etp_method.setObjectName("comboBox_etp_method")
        self.horizontalLayout.addWidget(self.comboBox_etp_method)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget_etp_method_params = QtWidgets.QTableWidget(Dialog_etp)
        self.tableWidget_etp_method_params.setMinimumSize(QtCore.QSize(300, 0))
        self.tableWidget_etp_method_params.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tableWidget_etp_method_params.setObjectName("tableWidget_etp_method_params")
        self.tableWidget_etp_method_params.setColumnCount(3)
        self.tableWidget_etp_method_params.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_etp_method_params.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_etp_method_params.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_etp_method_params.setHorizontalHeaderItem(2, item)
        self.tableWidget_etp_method_params.horizontalHeader().setDefaultSectionSize(90)
        self.verticalLayout.addWidget(self.tableWidget_etp_method_params)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_etp)
        self.buttonBox.setMaximumSize(QtCore.QSize(500, 16777215))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.groupBox_help = QtWidgets.QGroupBox(Dialog_etp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_help.sizePolicy().hasHeightForWidth())
        self.groupBox_help.setSizePolicy(sizePolicy)
        self.groupBox_help.setMinimumSize(QtCore.QSize(600, 500))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_help.setFont(font)
        self.groupBox_help.setAutoFillBackground(False)
        self.groupBox_help.setStyleSheet("QGroupBox{border:2px solid gray;border-radius:1px;margin-top: 1ex;}\n"
"QGroupBox::title{subcontrol-origin: margin;subcontrol-position:top center;padding:0 3px;}")
        self.groupBox_help.setTitle("Help")
        self.groupBox_help.setFlat(False)
        self.groupBox_help.setObjectName("groupBox_help")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_help)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.textBrowser_help = QtWidgets.QTextBrowser(self.groupBox_help)
        self.textBrowser_help.setAutoFillBackground(True)
        self.textBrowser_help.setStyleSheet("background-color: rgb(240, 240, 240)")
        self.textBrowser_help.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.textBrowser_help.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.textBrowser_help.setLineWidth(0)
        self.textBrowser_help.setReadOnly(True)
        self.textBrowser_help.setObjectName("textBrowser_help")
        self.horizontalLayout_16.addWidget(self.textBrowser_help)
        self.horizontalLayout_2.addWidget(self.groupBox_help)

        self.retranslateUi(Dialog_etp)
        self.buttonBox.accepted.connect(Dialog_etp.accept)
        self.buttonBox.rejected.connect(Dialog_etp.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_etp)

    def retranslateUi(self, Dialog_etp):
        _translate = QtCore.QCoreApplication.translate
        Dialog_etp.setWindowTitle(_translate("Dialog_etp", "ETP Calculation"))
        self.label_method.setText(_translate("Dialog_etp", "Method"))
        item = self.tableWidget_etp_method_params.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_etp", "Parameter"))
        item = self.tableWidget_etp_method_params.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_etp", "Type"))
        item = self.tableWidget_etp_method_params.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_etp", "Value or Path"))
        self.textBrowser_help.setHtml(_translate("Dialog_etp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.1pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_etp = QtWidgets.QDialog()
    ui = Ui_Dialog_etp()
    ui.setupUi(Dialog_etp)
    Dialog_etp.show()
    sys.exit(app.exec())
