# Form implementation generated from reading ui file 'waterpybalstudiointro_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_WaterPyBalStudio_intro(object):
    def setupUi(self, WaterPyBalStudio_intro):
        WaterPyBalStudio_intro.setObjectName("WaterPyBalStudio_intro")
        WaterPyBalStudio_intro.resize(1057, 615)
        WaterPyBalStudio_intro.setMinimumSize(QtCore.QSize(1057, 615))
        self.widget = QtWidgets.QWidget(WaterPyBalStudio_intro)
        self.widget.setGeometry(QtCore.QRect(20, 10, 1011, 602))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(400, 400))
        self.label.setMaximumSize(QtCore.QSize(400, 400))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("7_resized.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 35))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.textBrowser_help = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_help.setMinimumSize(QtCore.QSize(700, 800))
        self.textBrowser_help.setAutoFillBackground(True)
        self.textBrowser_help.setStyleSheet("background-color: rgb(240, 240, 240)")
        self.textBrowser_help.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.textBrowser_help.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.textBrowser_help.setLineWidth(0)
        self.textBrowser_help.setReadOnly(True)
        self.textBrowser_help.setObjectName("textBrowser_help")
        self.horizontalLayout_2.addWidget(self.textBrowser_help)

        self.retranslateUi(WaterPyBalStudio_intro)
        QtCore.QMetaObject.connectSlotsByName(WaterPyBalStudio_intro)

    def retranslateUi(self, WaterPyBalStudio_intro):
        _translate = QtCore.QCoreApplication.translate
        WaterPyBalStudio_intro.setWindowTitle(_translate("WaterPyBalStudio_intro", "WaterPyBal Studio"))
        self.pushButton.setText(_translate("WaterPyBalStudio_intro", "Enter WaterpyBal Studio"))
        self.textBrowser_help.setHtml(_translate("WaterPyBalStudio_intro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.1pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


'''if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaterPyBalStudio_intro = QtWidgets.QDialog()
    ui = Ui_WaterPyBalStudio_intro()
    ui.setupUi(WaterPyBalStudio_intro)
    WaterPyBalStudio_intro.show()
    sys.exit(app.exec())'''
